[project]
name = "ping_sweeper"
version = "0.3.0"
description = "A program to ping a range of IP addresses"
requires-python = ">=3.13"
dependencies = [
    "attrs",
    "loguru",
    "tqdm",
]

[project.optional-dependencies]
dev = [
    "black",
    "isort",
    "pylint",
]

[tool.black]
line-length = 120
target-version = ["py313"]

[tool.isort]
profile = "black"
line_length = 120

[tool.pylint.main]
ignore = [".venv", ".conda", "build"]
py-version = "3.13"

[tool.pylint.format]
max-line-length = 120
