[project]
name = "ping_sweeper"
version = "0.2.0"
description = "A program to ping a range of IP addresses"
requires-python = ">=3.13"
dependencies = [
    "tqdm",
]

[project.optional-dependencies]
dev = [
    "ruff",
    "pylint",
    "pytest",
]

[tool.ruff]
target-version = "py313"
line-length = 120
select = [
    "E", # Pycodestyle errors
    "F", # Pyflakes
    "I", # Isort
    "PL", # Pylint
    "UP", # Pyupgrade
]

[tool.pylint.format]
max-line-length = 120

[tool.pylint.main]
ignore = [".venv", ".conda", "build"]
py-version = "3.13"

[tool.setuptools]
packages = ["ping_sweeper"]
